services:
  finance-tools:
    image: finance-tools:latest
    build: .
    volumes:
      - .:/app # dismisses the need for -v "${PWD}:/app" flag for visualize_indicators.py
      - /app/node_modules
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true

  api-server:
    image: finance-api:latest
    build: .
    command: python -m api.api_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
